[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hy3dgen"
version = "2.0.2"
readme = "README.md"
license = "LicenseRef-Tencent-Hunyuan-Community"
license-files = ["LICENSE", "NOTICE"]
authors = [
    {name = "Hunyuan3D Team"},
    {name = "Tencent"},
]
dependencies = [
    "accelerate",
    "colorama",
    "diffusers",
    "einops",
    "fastapi",
    "huggingface-hub[hf-xet]",
    "ninja",
    "numpy==1.26.4",
    "omegaconf",
    "onnxruntime",
    "opencv-python==4.11.0.86",
    "pandas==2.0.3",
    "pybind11",
    "pygltflib",
    "pymeshlab",
    "rembg",
    "scipy",
    "tqdm>=4.66.3",
    "transformers>=4.48.0",
    "trimesh",
    "uvicorn",
    "xatlas",
]

[project.urls]
Homepage = "https://hunyuan-3d.com/"
Repository = "https://github.com/Tencent-Hunyuan/Hunyuan3D-2.git"

[tool.setuptools.packages]
find = {}